"""assessment narrative

Revision ID: 174d3fc1a80c
Revises: 19ac464d556d
Create Date: 2026-08-28 10:21:46.983029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174d3fc1a80c'
down_revision: Union[str, None] = '19ac464d556d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scout_assessments', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('scout_assessments', sa.Column('why_sign', sa.String(), nullable=True))
    op.add_column('scout_assessments', sa.Column('considerations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scout_assessments', 'considerations')
    op.drop_column('scout_assessments', 'why_sign')
    op.drop_column('scout_assessments', 'summary')
    # ### end Alembic commands ###
