"""phase 5: archetypes

Revision ID: 30d880905868
Revises: 57dfd0b711cc
Create Date: 2026-06-05 17:23:21.348559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d880905868'
down_revision: Union[str, None] = '57dfd0b711cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.String(), nullable=False),
    sa.Column('distance_to_centroid', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_archetype_player_competition_season')
    )
    op.create_index(op.f('ix_archetypes_cluster_label'), 'archetypes', ['cluster_label'], unique=False)
    op.create_index(op.f('ix_archetypes_competition_id'), 'archetypes', ['competition_id'], unique=False)
    op.create_index(op.f('ix_archetypes_player_id'), 'archetypes', ['player_id'], unique=False)
    op.create_index(op.f('ix_archetypes_position_group'), 'archetypes', ['position_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archetypes_position_group'), table_name='archetypes')
    op.drop_index(op.f('ix_archetypes_player_id'), table_name='archetypes')
    op.drop_index(op.f('ix_archetypes_competition_id'), table_name='archetypes')
    op.drop_index(op.f('ix_archetypes_cluster_label'), table_name='archetypes')
    op.drop_table('archetypes')
    # ### end Alembic commands ###
