"""phase 4: player_percentiles, player_scores

Revision ID: 57dfd0b711cc
Revises: 7408bdfcd11f
Create Date: 2026-06-05 14:57:13.351524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57dfd0b711cc'
down_revision: Union[str, None] = '7408bdfcd11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_percentiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', 'metric', name='uq_percentile_player_competition_season_metric')
    )
    op.create_index(op.f('ix_player_percentiles_competition_id'), 'player_percentiles', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_percentiles_metric'), 'player_percentiles', ['metric'], unique=False)
    op.create_index(op.f('ix_player_percentiles_player_id'), 'player_percentiles', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_percentiles_position_group'), 'player_percentiles', ['position_group'], unique=False)
    op.create_table('player_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('performance_rank', sa.Integer(), nullable=True),
    sa.Column('fit_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_score_player_competition_season')
    )
    op.create_index(op.f('ix_player_scores_competition_id'), 'player_scores', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_scores_player_id'), 'player_scores', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_scores_position_group'), 'player_scores', ['position_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_scores_position_group'), table_name='player_scores')
    op.drop_index(op.f('ix_player_scores_player_id'), table_name='player_scores')
    op.drop_index(op.f('ix_player_scores_competition_id'), table_name='player_scores')
    op.drop_table('player_scores')
    op.drop_index(op.f('ix_player_percentiles_position_group'), table_name='player_percentiles')
    op.drop_index(op.f('ix_player_percentiles_player_id'), table_name='player_percentiles')
    op.drop_index(op.f('ix_player_percentiles_metric'), table_name='player_percentiles')
    op.drop_index(op.f('ix_player_percentiles_competition_id'), table_name='player_percentiles')
    op.drop_table('player_percentiles')
    # ### end Alembic commands ###
