"""assessed composite

Revision ID: 5e80ab6fe191
Revises: a3fd42bcb2c2
Create Date: 2026-08-14 12:13:16.915112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e80ab6fe191'
down_revision: Union[str, None] = 'a3fd42bcb2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_scorecards', sa.Column('psychological_band', sa.Float(), nullable=True))
    op.add_column('player_scorecards', sa.Column('medical_band', sa.Float(), nullable=True))
    op.add_column('player_scorecards', sa.Column('assessed_composite', sa.Float(), nullable=True))
    op.add_column('player_scorecards', sa.Column('assessed_weight_covered', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_scorecards', 'assessed_weight_covered')
    op.drop_column('player_scorecards', 'assessed_composite')
    op.drop_column('player_scorecards', 'medical_band')
    op.drop_column('player_scorecards', 'psychological_band')
    # ### end Alembic commands ###
