"""player injuries

Revision ID: 6677cea28903
Revises: e2f7b91c6a55
Create Date: 2026-08-10 15:31:44.538099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6677cea28903'
down_revision: Union[str, None] = 'e2f7b91c6a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('tm_player_id', sa.BigInteger(), nullable=True),
    sa.Column('season_label', sa.String(), nullable=False),
    sa.Column('injury_type_raw', sa.String(), nullable=False),
    sa.Column('injury_category', sa.String(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_until', sa.Date(), nullable=True),
    sa.Column('days_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('games_missed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(), server_default='transfermarkt', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_injuries_injury_category'), 'player_injuries', ['injury_category'], unique=False)
    op.create_index(op.f('ix_player_injuries_player_id'), 'player_injuries', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_injuries_tm_player_id'), 'player_injuries', ['tm_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_injuries_tm_player_id'), table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_player_id'), table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_injury_category'), table_name='player_injuries')
    op.drop_table('player_injuries')
    # ### end Alembic commands ###
