"""player_metrics_neutral (Phase 11 combined table)

Revision ID: 71204e85d2fb
Revises: 8298a17dd305
Create Date: 2026-07-20 10:21:36.443975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71204e85d2fb'
down_revision: Union[str, None] = '8298a17dd305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_metrics_neutral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('rankable', sa.Boolean(), nullable=False),
    sa.Column('goals_p90', sa.Float(), nullable=True),
    sa.Column('np_xg_p90', sa.Float(), nullable=True),
    sa.Column('shots_p90', sa.Float(), nullable=True),
    sa.Column('xa_p90', sa.Float(), nullable=True),
    sa.Column('assists_p90', sa.Float(), nullable=True),
    sa.Column('key_passes_p90', sa.Float(), nullable=True),
    sa.Column('xg_overperformance_p90', sa.Float(), nullable=True),
    sa.Column('touches_in_box_p90', sa.Float(), nullable=True),
    sa.Column('open_play_assists_p90', sa.Float(), nullable=True),
    sa.Column('np_xg_xa_p90', sa.Float(), nullable=True),
    sa.Column('post_shot_xg_p90', sa.Float(), nullable=True),
    sa.Column('shot_threat_p90', sa.Float(), nullable=True),
    sa.Column('passes_completed_p90', sa.Float(), nullable=True),
    sa.Column('passes_into_box_p90', sa.Float(), nullable=True),
    sa.Column('pass_completion_pct', sa.Float(), nullable=True),
    sa.Column('goal_conversion_pct', sa.Float(), nullable=True),
    sa.Column('xg_per_shot', sa.Float(), nullable=True),
    sa.Column('pass_value_p90', sa.Float(), nullable=True),
    sa.Column('dribble_carry_value_p90', sa.Float(), nullable=True),
    sa.Column('defensive_value_p90', sa.Float(), nullable=True),
    sa.Column('on_ball_value_p90', sa.Float(), nullable=True),
    sa.Column('packing_bypassed_opponents_p90', sa.Float(), nullable=True),
    sa.Column('packing_bypassed_defenders_p90', sa.Float(), nullable=True),
    sa.Column('packing_xg_p90', sa.Float(), nullable=True),
    sa.Column('ground_duels_won_p90', sa.Float(), nullable=True),
    sa.Column('ball_wins_p90', sa.Float(), nullable=True),
    sa.Column('turnovers_p90', sa.Float(), nullable=True),
    sa.Column('off_ball_receiving_p90', sa.Float(), nullable=True),
    sa.Column('pressures_p90', sa.Float(), nullable=True),
    sa.Column('counterpressures_p90', sa.Float(), nullable=True),
    sa.Column('deep_progressions_p90', sa.Float(), nullable=True),
    sa.Column('aerial_win_pct', sa.Float(), nullable=True),
    sa.Column('ground_duel_win_pct', sa.Float(), nullable=True),
    sa.Column('gk_conceded_p90', sa.Float(), nullable=True),
    sa.Column('gk_gsaa_p90', sa.Float(), nullable=True),
    sa.Column('gk_shot_stopping_pct', sa.Float(), nullable=True),
    sa.Column('pressures_opp_half_p90', sa.Float(), nullable=True),
    sa.Column('aggressive_actions_p90', sa.Float(), nullable=True),
    sa.Column('padj_tackles_interceptions_p90', sa.Float(), nullable=True),
    sa.Column('padj_pressures_p90', sa.Float(), nullable=True),
    sa.Column('xg_buildup_p90', sa.Float(), nullable=True),
    sa.Column('pressured_pass_pct', sa.Float(), nullable=True),
    sa.Column('successful_box_cross_pct', sa.Float(), nullable=True),
    sa.Column('dribbles_p90', sa.Float(), nullable=True),
    sa.Column('dribble_success_pct', sa.Float(), nullable=True),
    sa.Column('gk_claims_pct', sa.Float(), nullable=True),
    sa.Column('gk_aggressive_distance', sa.Float(), nullable=True),
    sa.Column('long_ball_pct', sa.Float(), nullable=True),
    sa.Column('tackles_p90', sa.Float(), nullable=True),
    sa.Column('interceptions_p90', sa.Float(), nullable=True),
    sa.Column('blocks_p90', sa.Float(), nullable=True),
    sa.Column('clearances_p90', sa.Float(), nullable=True),
    sa.Column('ball_recoveries_p90', sa.Float(), nullable=True),
    sa.Column('carries_p90', sa.Float(), nullable=True),
    sa.Column('progressive_carries_p90', sa.Float(), nullable=True),
    sa.Column('progressive_passes_p90', sa.Float(), nullable=True),
    sa.Column('passes_into_final_third_p90', sa.Float(), nullable=True),
    sa.Column('passes_p90', sa.Float(), nullable=True),
    sa.Column('dribbles_completed_p90', sa.Float(), nullable=True),
    sa.Column('np_goals_p90', sa.Float(), nullable=True),
    sa.Column('xg_p90', sa.Float(), nullable=True),
    sa.Column('gk_saves_p90', sa.Float(), nullable=True),
    sa.Column('save_pct', sa.Float(), nullable=True),
    sa.Column('distance_p90', sa.Float(), nullable=True),
    sa.Column('meters_per_minute', sa.Float(), nullable=True),
    sa.Column('running_distance_p90', sa.Float(), nullable=True),
    sa.Column('hsr_distance_p90', sa.Float(), nullable=True),
    sa.Column('sprint_distance_p90', sa.Float(), nullable=True),
    sa.Column('hi_distance_p90', sa.Float(), nullable=True),
    sa.Column('hsr_count_p90', sa.Float(), nullable=True),
    sa.Column('sprint_count_p90', sa.Float(), nullable=True),
    sa.Column('hi_count_p90', sa.Float(), nullable=True),
    sa.Column('cod_count_p90', sa.Float(), nullable=True),
    sa.Column('psv99_kmh', sa.Float(), nullable=True),
    sa.Column('top5_psv99_kmh', sa.Float(), nullable=True),
    sa.Column('medium_accel_count_p90', sa.Float(), nullable=True),
    sa.Column('high_accel_count_p90', sa.Float(), nullable=True),
    sa.Column('medium_decel_count_p90', sa.Float(), nullable=True),
    sa.Column('high_decel_count_p90', sa.Float(), nullable=True),
    sa.Column('explosive_accel_to_hsr_p90', sa.Float(), nullable=True),
    sa.Column('explosive_accel_to_sprint_p90', sa.Float(), nullable=True),
    sa.Column('time_to_hsr', sa.Float(), nullable=True),
    sa.Column('time_to_hsr_post_cod', sa.Float(), nullable=True),
    sa.Column('time_to_sprint', sa.Float(), nullable=True),
    sa.Column('time_to_sprint_post_cod', sa.Float(), nullable=True),
    sa.Column('agility_505_90', sa.Float(), nullable=True),
    sa.Column('agility_505_180', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_neutral_player_comp_season')
    )
    op.create_index(op.f('ix_player_metrics_neutral_competition_id'), 'player_metrics_neutral', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_metrics_neutral_player_id'), 'player_metrics_neutral', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_metrics_neutral_season_id'), 'player_metrics_neutral', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_metrics_neutral_season_id'), table_name='player_metrics_neutral')
    op.drop_index(op.f('ix_player_metrics_neutral_player_id'), table_name='player_metrics_neutral')
    op.drop_index(op.f('ix_player_metrics_neutral_competition_id'), table_name='player_metrics_neutral')
    op.drop_table('player_metrics_neutral')
    # ### end Alembic commands ###
