"""core schema: players, metrics, wage_framework, identity_profiles

Revision ID: 7408bdfcd11f
Revises: 0001_baseline
Create Date: 2026-06-05 13:15:17.463226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7408bdfcd11f'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('min_percentile', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_group', 'metric', name='uq_position_metric')
    )
    op.create_index(op.f('ix_identity_profiles_position_group'), 'identity_profiles', ['position_group'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('wage_framework',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('age_band', sa.String(), nullable=False),
    sa.Column('weekly_wage_ceiling_gbp', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_group', 'age_band', name='uq_position_age_band')
    )
    op.create_index(op.f('ix_wage_framework_position_group'), 'wage_framework', ['position_group'], unique=False)
    op.create_table('player_season_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('competition_name', sa.String(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('dominant_position_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('rankable', sa.Boolean(), nullable=False),
    sa.Column('goals', sa.Float(), nullable=False),
    sa.Column('np_goals', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('shots', sa.Float(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=False),
    sa.Column('np_xg', sa.Float(), nullable=False),
    sa.Column('xa', sa.Float(), nullable=False),
    sa.Column('goals_p90', sa.Float(), nullable=False),
    sa.Column('np_goals_p90', sa.Float(), nullable=False),
    sa.Column('xg_p90', sa.Float(), nullable=False),
    sa.Column('np_xg_p90', sa.Float(), nullable=False),
    sa.Column('shots_p90', sa.Float(), nullable=False),
    sa.Column('assists_p90', sa.Float(), nullable=False),
    sa.Column('xa_p90', sa.Float(), nullable=False),
    sa.Column('key_passes_p90', sa.Float(), nullable=False),
    sa.Column('passes_p90', sa.Float(), nullable=False),
    sa.Column('passes_completed_p90', sa.Float(), nullable=False),
    sa.Column('progressive_passes_p90', sa.Float(), nullable=False),
    sa.Column('passes_into_final_third_p90', sa.Float(), nullable=False),
    sa.Column('passes_into_box_p90', sa.Float(), nullable=False),
    sa.Column('dribbles_p90', sa.Float(), nullable=False),
    sa.Column('dribbles_completed_p90', sa.Float(), nullable=False),
    sa.Column('carries_p90', sa.Float(), nullable=False),
    sa.Column('progressive_carries_p90', sa.Float(), nullable=False),
    sa.Column('pressures_p90', sa.Float(), nullable=False),
    sa.Column('tackles_p90', sa.Float(), nullable=False),
    sa.Column('interceptions_p90', sa.Float(), nullable=False),
    sa.Column('blocks_p90', sa.Float(), nullable=False),
    sa.Column('clearances_p90', sa.Float(), nullable=False),
    sa.Column('ball_recoveries_p90', sa.Float(), nullable=False),
    sa.Column('gk_saves_p90', sa.Float(), nullable=False),
    sa.Column('pass_completion_pct', sa.Float(), nullable=True),
    sa.Column('dribble_success_pct', sa.Float(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('save_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_player_competition_season')
    )
    op.create_index(op.f('ix_player_season_metrics_competition_id'), 'player_season_metrics', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_season_metrics_player_id'), 'player_season_metrics', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_metrics_position_group'), 'player_season_metrics', ['position_group'], unique=False)
    op.create_index(op.f('ix_player_season_metrics_rankable'), 'player_season_metrics', ['rankable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_season_metrics_rankable'), table_name='player_season_metrics')
    op.drop_index(op.f('ix_player_season_metrics_position_group'), table_name='player_season_metrics')
    op.drop_index(op.f('ix_player_season_metrics_player_id'), table_name='player_season_metrics')
    op.drop_index(op.f('ix_player_season_metrics_competition_id'), table_name='player_season_metrics')
    op.drop_table('player_season_metrics')
    op.drop_index(op.f('ix_wage_framework_position_group'), table_name='wage_framework')
    op.drop_table('wage_framework')
    op.drop_table('players')
    op.drop_index(op.f('ix_identity_profiles_position_group'), table_name='identity_profiles')
    op.drop_table('identity_profiles')
    # ### end Alembic commands ###
