"""players tm_player_id for profile links

Revision ID: 8298a17dd305
Revises: e3f9ffc5dff5
Create Date: 2026-06-10 22:37:42.014811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8298a17dd305'
down_revision: Union[str, None] = 'e3f9ffc5dff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('tm_player_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'tm_player_id')
    # ### end Alembic commands ###
