"""phase 6: valuations

Revision ID: 9a455e99c328
Revises: 30d880905868
Create Date: 2026-06-06 13:45:17.393597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a455e99c328'
down_revision: Union[str, None] = '30d880905868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('market_value_eur', sa.Float(), nullable=False),
    sa.Column('fair_value_eur', sa.Float(), nullable=False),
    sa.Column('undervaluation_eur', sa.Float(), nullable=False),
    sa.Column('undervaluation_pct', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_valuation_player_competition_season')
    )
    op.create_index(op.f('ix_valuations_competition_id'), 'valuations', ['competition_id'], unique=False)
    op.create_index(op.f('ix_valuations_player_id'), 'valuations', ['player_id'], unique=False)
    op.create_index(op.f('ix_valuations_position_group'), 'valuations', ['position_group'], unique=False)
    op.create_index(op.f('ix_valuations_undervaluation_pct'), 'valuations', ['undervaluation_pct'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_undervaluation_pct'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_position_group'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_player_id'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_competition_id'), table_name='valuations')
    op.drop_table('valuations')
    # ### end Alembic commands ###
