"""scout assessments

Revision ID: a3fd42bcb2c2
Revises: 6677cea28903
Create Date: 2026-08-14 11:27:09.608864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fd42bcb2c2'
down_revision: Union[str, None] = '6677cea28903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('scout_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('band', sa.Float(), nullable=True),
    sa.Column('band_note', sa.String(), nullable=True),
    sa.Column('screening_failed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scout_assessments_competition_id'), 'scout_assessments', ['competition_id'], unique=False)
    op.create_index(op.f('ix_scout_assessments_dimension'), 'scout_assessments', ['dimension'], unique=False)
    op.create_index(op.f('ix_scout_assessments_player_id'), 'scout_assessments', ['player_id'], unique=False)
    op.create_index(op.f('ix_scout_assessments_season_id'), 'scout_assessments', ['season_id'], unique=False)
    op.create_table('scout_criterion_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('criterion_key', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['scout_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scout_criterion_scores_assessment_id'), 'scout_criterion_scores', ['assessment_id'], unique=False)
    op.add_column('player_injuries', sa.Column('entered_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player_injuries', 'users', ['entered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_injuries', type_='foreignkey')
    op.drop_column('player_injuries', 'entered_by')
    op.drop_index(op.f('ix_scout_criterion_scores_assessment_id'), table_name='scout_criterion_scores')
    op.drop_table('scout_criterion_scores')
    op.drop_index(op.f('ix_scout_assessments_season_id'), table_name='scout_assessments')
    op.drop_index(op.f('ix_scout_assessments_player_id'), table_name='scout_assessments')
    op.drop_index(op.f('ix_scout_assessments_dimension'), table_name='scout_assessments')
    op.drop_index(op.f('ix_scout_assessments_competition_id'), table_name='scout_assessments')
    op.drop_table('scout_assessments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
