"""transfermarkt squad snapshot table

Moves the Transfermarkt squad scrape out of a local CSV and into Postgres, so the dashboard
reads a table rather than a file on the app process's own disk. See store/squads.py for why.

Autogenerate also proposed altering player_loans.scraped_at to NOT NULL -- pre-existing drift
between the model and the database, unrelated to this change, deliberately left out.

Revision ID: a73c68b15b48
Revises: c8f1d20a4e65
Create Date: 2026-09-11 10:47:06.053489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = 'a73c68b15b48'
down_revision: Union[str, None] = 'c8f1d20a4e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfermarkt_squads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tm_player_id', sa.BigInteger(), nullable=False),
    sa.Column('league_code', sa.String(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('foot', sa.String(), nullable=True),
    sa.Column('contract_until', sa.Date(), nullable=True),
    sa.Column('market_value_eur', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfermarkt_squads_club_name'), 'transfermarkt_squads', ['club_name'], unique=False)
    op.create_index(op.f('ix_transfermarkt_squads_competition_id'), 'transfermarkt_squads', ['competition_id'], unique=False)
    op.create_index(op.f('ix_transfermarkt_squads_tm_player_id'), 'transfermarkt_squads', ['tm_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfermarkt_squads_tm_player_id'), table_name='transfermarkt_squads')
    op.drop_index(op.f('ix_transfermarkt_squads_competition_id'), table_name='transfermarkt_squads')
    op.drop_index(op.f('ix_transfermarkt_squads_club_name'), table_name='transfermarkt_squads')
    op.drop_table('transfermarkt_squads')
    # ### end Alembic commands ###
