"""phase 10: league-aware wage estimate bands

Revision ID: bc5591accb97
Revises: cdef4ad8fbaf
Create Date: 2026-06-10 01:21:59.703768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5591accb97'
down_revision: Union[str, None] = 'cdef4ad8fbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # wage_estimates is regenerated reference data; clear it so the new non-nullable
    # columns can be added, then the next pipeline load refills it league-aware.
    op.execute('DELETE FROM wage_estimates')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlists', sa.Column('wage_low_gbp', sa.Integer(), nullable=True))
    op.add_column('shortlists', sa.Column('wage_high_gbp', sa.Integer(), nullable=True))
    op.add_column('shortlists', sa.Column('wage_marginal', sa.Boolean(), nullable=True))
    op.add_column('wage_estimates', sa.Column('competition_id', sa.Integer(), nullable=False))
    op.add_column('wage_estimates', sa.Column('wage_low_gbp', sa.Integer(), nullable=False))
    op.add_column('wage_estimates', sa.Column('wage_high_gbp', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_wage_estimate_position_age_tier'), 'wage_estimates', type_='unique')
    op.create_index(op.f('ix_wage_estimates_competition_id'), 'wage_estimates', ['competition_id'], unique=False)
    op.create_unique_constraint('uq_wage_estimate_league_position_age_tier', 'wage_estimates', ['competition_id', 'position_group', 'age_band', 'performance_tier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wage_estimate_league_position_age_tier', 'wage_estimates', type_='unique')
    op.drop_index(op.f('ix_wage_estimates_competition_id'), table_name='wage_estimates')
    op.create_unique_constraint(op.f('uq_wage_estimate_position_age_tier'), 'wage_estimates', ['position_group', 'age_band', 'performance_tier'], postgresql_nulls_not_distinct=False)
    op.drop_column('wage_estimates', 'wage_high_gbp')
    op.drop_column('wage_estimates', 'wage_low_gbp')
    op.drop_column('wage_estimates', 'competition_id')
    op.drop_column('shortlists', 'wage_marginal')
    op.drop_column('shortlists', 'wage_high_gbp')
    op.drop_column('shortlists', 'wage_low_gbp')
    # ### end Alembic commands ###
