"""phase 10b: skillcorner physical tables

Revision ID: bfde29b7bd77
Revises: bc5591accb97
Create Date: 2026-06-10 18:09:08.469718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfde29b7bd77'
down_revision: Union[str, None] = 'bc5591accb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skillcorner_team_season',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sc_team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('season_label', sa.String(), nullable=False),
    sa.Column('matches_measured', sa.Integer(), nullable=False),
    sa.Column('avg_minutes', sa.Float(), nullable=True),
    sa.Column('distance_p90', sa.Float(), nullable=True),
    sa.Column('m_per_min_p90', sa.Float(), nullable=True),
    sa.Column('running_distance_p90', sa.Float(), nullable=True),
    sa.Column('hsr_distance_p90', sa.Float(), nullable=True),
    sa.Column('hsr_count_p90', sa.Float(), nullable=True),
    sa.Column('sprint_distance_p90', sa.Float(), nullable=True),
    sa.Column('sprint_count_p90', sa.Float(), nullable=True),
    sa.Column('hi_distance_p90', sa.Float(), nullable=True),
    sa.Column('hi_count_p90', sa.Float(), nullable=True),
    sa.Column('psv99_kmh', sa.Float(), nullable=True),
    sa.Column('top5_psv99_kmh', sa.Float(), nullable=True),
    sa.Column('medium_accel_count_p90', sa.Float(), nullable=True),
    sa.Column('high_accel_count_p90', sa.Float(), nullable=True),
    sa.Column('medium_decel_count_p90', sa.Float(), nullable=True),
    sa.Column('high_decel_count_p90', sa.Float(), nullable=True),
    sa.Column('explosive_accel_to_hsr_p90', sa.Float(), nullable=True),
    sa.Column('explosive_accel_to_sprint_p90', sa.Float(), nullable=True),
    sa.Column('cod_count_p90', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sc_team_id', 'season_label', name='uq_sc_team_season')
    )
    op.create_index(op.f('ix_skillcorner_team_season_sc_team_id'), 'skillcorner_team_season', ['sc_team_id'], unique=False)
    op.create_index(op.f('ix_skillcorner_team_season_team_name'), 'skillcorner_team_season', ['team_name'], unique=False)
    op.create_table('skillcorner_player_season',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sc_player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('season_label', sa.String(), nullable=False),
    sa.Column('matches_measured', sa.Integer(), nullable=False),
    sa.Column('avg_minutes', sa.Float(), nullable=True),
    sa.Column('distance_p90', sa.Float(), nullable=True),
    sa.Column('m_per_min_p90', sa.Float(), nullable=True),
    sa.Column('running_distance_p90', sa.Float(), nullable=True),
    sa.Column('hsr_distance_p90', sa.Float(), nullable=True),
    sa.Column('hsr_count_p90', sa.Float(), nullable=True),
    sa.Column('sprint_distance_p90', sa.Float(), nullable=True),
    sa.Column('sprint_count_p90', sa.Float(), nullable=True),
    sa.Column('hi_distance_p90', sa.Float(), nullable=True),
    sa.Column('hi_count_p90', sa.Float(), nullable=True),
    sa.Column('psv99_kmh', sa.Float(), nullable=True),
    sa.Column('top5_psv99_kmh', sa.Float(), nullable=True),
    sa.Column('medium_accel_count_p90', sa.Float(), nullable=True),
    sa.Column('high_accel_count_p90', sa.Float(), nullable=True),
    sa.Column('medium_decel_count_p90', sa.Float(), nullable=True),
    sa.Column('high_decel_count_p90', sa.Float(), nullable=True),
    sa.Column('explosive_accel_to_hsr_p90', sa.Float(), nullable=True),
    sa.Column('explosive_accel_to_sprint_p90', sa.Float(), nullable=True),
    sa.Column('cod_count_p90', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sc_player_id', 'season_label', name='uq_sc_player_season')
    )
    op.create_index(op.f('ix_skillcorner_player_season_player_id'), 'skillcorner_player_season', ['player_id'], unique=False)
    op.create_index(op.f('ix_skillcorner_player_season_player_name'), 'skillcorner_player_season', ['player_name'], unique=False)
    op.create_index(op.f('ix_skillcorner_player_season_sc_player_id'), 'skillcorner_player_season', ['sc_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skillcorner_player_season_sc_player_id'), table_name='skillcorner_player_season')
    op.drop_index(op.f('ix_skillcorner_player_season_player_name'), table_name='skillcorner_player_season')
    op.drop_index(op.f('ix_skillcorner_player_season_player_id'), table_name='skillcorner_player_season')
    op.drop_table('skillcorner_player_season')
    op.drop_index(op.f('ix_skillcorner_team_season_team_name'), table_name='skillcorner_team_season')
    op.drop_index(op.f('ix_skillcorner_team_season_sc_team_id'), table_name='skillcorner_team_season')
    op.drop_table('skillcorner_team_season')
    # ### end Alembic commands ###
