"""player bio: foot, contract, height

Revision ID: c425fb38ba1f
Revises: bfde29b7bd77
Create Date: 2026-06-10 20:28:08.690078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c425fb38ba1f'
down_revision: Union[str, None] = 'bfde29b7bd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('foot', sa.String(), nullable=True))
    op.add_column('players', sa.Column('contract_until', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('height_cm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'height_cm')
    op.drop_column('players', 'contract_until')
    op.drop_column('players', 'foot')
    # ### end Alembic commands ###
