"""phase 7: wage_estimates, shortlists

Revision ID: cdef4ad8fbaf
Revises: 9a455e99c328
Create Date: 2026-06-06 14:49:12.958694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef4ad8fbaf'
down_revision: Union[str, None] = '9a455e99c328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage_estimates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('age_band', sa.String(), nullable=False),
    sa.Column('performance_tier', sa.String(), nullable=False),
    sa.Column('estimated_weekly_wage_gbp', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_group', 'age_band', 'performance_tier', name='uq_wage_estimate_position_age_tier')
    )
    op.create_index(op.f('ix_wage_estimates_position_group'), 'wage_estimates', ['position_group'], unique=False)
    op.create_table('shortlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('affordable_fee', sa.Boolean(), nullable=False),
    sa.Column('affordable_wage', sa.Boolean(), nullable=False),
    sa.Column('on_profile', sa.Boolean(), nullable=False),
    sa.Column('is_near_miss', sa.Boolean(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('undervaluation_pct', sa.Float(), nullable=True),
    sa.Column('market_value_eur', sa.Float(), nullable=True),
    sa.Column('estimated_weekly_wage_gbp', sa.Integer(), nullable=True),
    sa.Column('wage_ceiling_gbp', sa.Integer(), nullable=True),
    sa.Column('transfer_budget_eur', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_shortlist_player_competition_season')
    )
    op.create_index(op.f('ix_shortlists_competition_id'), 'shortlists', ['competition_id'], unique=False)
    op.create_index(op.f('ix_shortlists_is_near_miss'), 'shortlists', ['is_near_miss'], unique=False)
    op.create_index(op.f('ix_shortlists_player_id'), 'shortlists', ['player_id'], unique=False)
    op.create_index(op.f('ix_shortlists_position_group'), 'shortlists', ['position_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortlists_position_group'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_player_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_is_near_miss'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_competition_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_wage_estimates_position_group'), table_name='wage_estimates')
    op.drop_table('wage_estimates')
    # ### end Alembic commands ###
