"""watchlist user table

Revision ID: e3f9ffc5dff5
Revises: c425fb38ba1f
Create Date: 2026-06-10 22:19:30.971485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f9ffc5dff5'
down_revision: Union[str, None] = 'c425fb38ba1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='Watching', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'competition_id', 'season_id', name='uq_watchlist_player_competition_season')
    )
    op.create_index(op.f('ix_watchlist_competition_id'), 'watchlist', ['competition_id'], unique=False)
    op.create_index(op.f('ix_watchlist_player_id'), 'watchlist', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_player_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_competition_id'), table_name='watchlist')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
